TELEGRAM_BOT_TOKEN = "5272643810:AAEjOe7Nynv59EiIF6Ec_iXOQanv_BM_ShcE" #prod
TELEGRAM_BOT_TOKEN = "1677807470:AAGvn3Ctoootxr0tKYlGBXw8JY-2_YuYZhI" #test

LOGGING_MESSAGES_FILE = "messages.txt"
LOGGING_ACTIONS_FILE = "actions.txt"
LOGGING_ACTIONS = True

BD_FILE_NAME = "bicycle.db"