TELEGRAM_BOT_TOKEN = ""

LOGGING_MESSAGES_FILE = "messages.txt"
LOGGING_ACTIONS_FILE = "actions.txt"
LOGGING_ACTIONS = True

BD_FILE_NAME = "bicycle.db"

ADMIN_IDS = [328076442]

NOTICE_ID = 328076442

QIWI_LOGIN = ""
QIWI_TOKEN = ""
QIWI_KEY = ""